name: CI

on: [push]

jobs:

  main:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - uses: actions/checkout@master
      - name: Install  Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'    
      
      - name: NPM Install
        run: npm install
        env:
          CI: true

      - name: Login to docker registery
        uses: azure/docker-login@master
        with:
          login-server: ${{ secrets.DOCKER_REGISTERY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push docker container to registry
        run: |
          docker build . -t ${{ secrets.DOCKER_REGISTERY_URL }}/alfred_lights_service:${{ github.sha }}
          docker push ${{ secrets.DOCKER_REGISTERY_URL }}/alfred_lights_service:${{ github.sha }}
  