name: CI

on: [push]

jobs:

  main:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - uses: actions/checkout@master
      - name: Get Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'    
      
      - name: NPM Install
        run: npm install
        env:
          CI: true

      - name: Build and publish docker container to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: alfred_lights_service
          registry: ${{ secrets.DOCKER_REGISTERY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}