name: CI

on: [push]

jobs:

  main:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - uses: actions/checkout@master
      - name: Install  Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'    
      
      - name: NPM Install
        run: npm install
        env:
          CI: true

      - name: Create CA cert folder
        run: |
          sudo echo { "insecure-registries": ["${{ secrets.DOCKER_REGISTERY_URL }}"] } > /etc/docker/daemon.json
          sudo cat /etc/docker/daemon.json

      - name: Login to docker registery
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTERY_URL }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin 
    
      - name: Build & push docker container to registry
        run: |
          docker build . -t ${{ secrets.DOCKER_REGISTERY_URL }}/alfred_lights_service:${{ github.sha }}
          docker push ${{ secrets.DOCKER_REGISTERY_URL }}/alfred_lights_service:${{ github.sha }}
  